import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const SEMVER = /^\d+\.\d+\.\d+$/

/** A parsed eve SKILL.md: only `description` and string `metadata` are meaningful (eve skills docs). */
export interface SkillFile {
  name: string
  description: string
  version: string
  body: string
}

/** Parses the subset of YAML frontmatter eve reads: `description` and `metadata.version`. */
export function parseSkillFile(name: string, source: string): SkillFile {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/.exec(source)
  if (!m) throw new Error(`${name}: SKILL.md needs YAML frontmatter`)
  const front = m[1] ?? ''
  const description = /^description:\s*(.+)$/m.exec(front)?.[1]?.trim()
  const version = /^\s+version:\s*"?([^"\n]+)"?\s*$/m.exec(front)?.[1]?.trim()
  if (!description) throw new Error(`${name}: frontmatter needs a description`)
  if (!version || !SEMVER.test(version)) throw new Error(`${name}: frontmatter needs metadata.version as semver`)
  return { name, description, version, body: (m[2] ?? '').trim() }
}

/** Reads every skills/<name>/SKILL.md and writes agent/lib/skills/generated.ts (gitignored). */
function main(): void {
  const root = fileURLToPath(new URL('..', import.meta.url))
  const dir = join(root, 'skills')
  const files = readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => parseSkillFile(d.name, readFileSync(join(dir, d.name, 'SKILL.md'), 'utf8')))
  const out = `// Generated by scripts/bundle-skills.ts from skills/*/SKILL.md. Do not edit.\nexport const SKILL_FILES = ${JSON.stringify(Object.fromEntries(files.map((f) => [f.name, f])), null, 2)} as const\n`
  writeFileSync(join(root, 'agent/lib/skills/generated.ts'), out)
}

if (import.meta.main) main()
